
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label NOMBRE;
	private global::Gtk.Label GRUPO;
	private global::Gtk.Entry entry1;
	private global::Gtk.Entry entry2;
	private global::Gtk.Label CODIGO;
	private global::Gtk.ComboBox combobox1;
	private global::Gtk.Label lblpregunta1;
	private global::Gtk.Label label5;
	private global::Gtk.RadioButton opca;
	private global::Gtk.Label label6;
	private global::Gtk.RadioButton opcb;
	private global::Gtk.Label label7;
	private global::Gtk.RadioButton opcc;
	private global::Gtk.Label lblpregunta2;
	private global::Gtk.SpinButton sum1;
	private global::Gtk.Label lblpregunta3;
	private global::Gtk.Label label10;
	private global::Gtk.CheckButton mexico;
	private global::Gtk.Label label11;
	private global::Gtk.CheckButton españa;
	private global::Gtk.Label label12;
	private global::Gtk.CheckButton japon;
	private global::Gtk.Label label13;
	private global::Gtk.CheckButton argentina;
	private global::Gtk.Label lblpregunta4;
	private global::Gtk.Calendar calendario;
	private global::Gtk.Button botonterminar;
	private global::Gtk.Entry entry3;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.NOMBRE = new global::Gtk.Label ();
		this.NOMBRE.Name = "NOMBRE";
		this.NOMBRE.LabelProp = global::Mono.Unix.Catalog.GetString ("NOMBRE");
		this.fixed1.Add (this.NOMBRE);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.NOMBRE]));
		w1.X = 14;
		w1.Y = 16;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GRUPO = new global::Gtk.Label ();
		this.GRUPO.Name = "GRUPO";
		this.GRUPO.LabelProp = global::Mono.Unix.Catalog.GetString ("GRUPO");
		this.fixed1.Add (this.GRUPO);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GRUPO]));
		w2.X = 283;
		w2.Y = 45;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.fixed1.Add (this.entry1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry1]));
		w3.X = 83;
		w3.Y = 12;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry2 = new global::Gtk.Entry ();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '●';
		this.fixed1.Add (this.entry2);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry2]));
		w4.X = 82;
		w4.Y = 48;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CODIGO = new global::Gtk.Label ();
		this.CODIGO.Name = "CODIGO";
		this.CODIGO.LabelProp = global::Mono.Unix.Catalog.GetString ("CODIGO");
		this.fixed1.Add (this.CODIGO);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CODIGO]));
		w5.X = 17;
		w5.Y = 53;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.combobox1 = global::Gtk.ComboBox.NewText ();
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("a"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("b"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("c"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("d"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("e"));
		this.combobox1.Name = "combobox1";
		this.fixed1.Add (this.combobox1);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.combobox1]));
		w6.X = 350;
		w6.Y = 40;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblpregunta1 = new global::Gtk.Label ();
		this.lblpregunta1.Name = "lblpregunta1";
		this.lblpregunta1.LabelProp = global::Mono.Unix.Catalog.GetString ("1-. ¿Cual es el nombe de profesor de programacion 3?");
		this.fixed1.Add (this.lblpregunta1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblpregunta1]));
		w7.X = 17;
		w7.Y = 96;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("a)");
		this.fixed1.Add (this.label5);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
		w8.X = 14;
		w8.Y = 125;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.opca = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Jesus Cabrera"));
		this.opca.CanFocus = true;
		this.opca.Name = "opca";
		this.opca.DrawIndicator = true;
		this.opca.UseUnderline = true;
		this.opca.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.fixed1.Add (this.opca);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.opca]));
		w9.X = 29;
		w9.Y = 125;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("b)");
		this.fixed1.Add (this.label6);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label6]));
		w10.X = 179;
		w10.Y = 127;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.opcb = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Cesar Carrion "));
		this.opcb.CanFocus = true;
		this.opcb.Name = "opcb";
		this.opcb.DrawIndicator = true;
		this.opcb.UseUnderline = true;
		this.opcb.Group = this.opca.Group;
		this.fixed1.Add (this.opcb);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.opcb]));
		w11.X = 197;
		w11.Y = 126;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("c)");
		this.fixed1.Add (this.label7);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label7]));
		w12.X = 342;
		w12.Y = 127;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.opcc = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Jonathan Lopez"));
		this.opcc.CanFocus = true;
		this.opcc.Name = "opcc";
		this.opcc.DrawIndicator = true;
		this.opcc.UseUnderline = true;
		this.opcc.Group = this.opca.Group;
		this.fixed1.Add (this.opcc);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.opcc]));
		w13.X = 362;
		w13.Y = 127;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblpregunta2 = new global::Gtk.Label ();
		this.lblpregunta2.Name = "lblpregunta2";
		this.lblpregunta2.LabelProp = global::Mono.Unix.Catalog.GetString ("2-.¿Cuanto es 2+2?");
		this.fixed1.Add (this.lblpregunta2);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblpregunta2]));
		w14.X = 20;
		w14.Y = 158;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.sum1 = new global::Gtk.SpinButton (0D, 100D, 1D);
		this.sum1.CanFocus = true;
		this.sum1.Name = "sum1";
		this.sum1.Adjustment.PageIncrement = 10D;
		this.sum1.ClimbRate = 1D;
		this.sum1.Numeric = true;
		this.sum1.Value = 3D;
		this.fixed1.Add (this.sum1);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.sum1]));
		w15.X = 41;
		w15.Y = 184;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblpregunta3 = new global::Gtk.Label ();
		this.lblpregunta3.Name = "lblpregunta3";
		this.lblpregunta3.LabelProp = global::Mono.Unix.Catalog.GetString ("3-. De los sig. paises ¿Cuales son de America?");
		this.fixed1.Add (this.lblpregunta3);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblpregunta3]));
		w16.X = 18;
		w16.Y = 220;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("a)");
		this.fixed1.Add (this.label10);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label10]));
		w17.X = 16;
		w17.Y = 246;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.mexico = new global::Gtk.CheckButton ();
		this.mexico.CanFocus = true;
		this.mexico.Name = "mexico";
		this.mexico.Label = global::Mono.Unix.Catalog.GetString ("Mexico");
		this.mexico.DrawIndicator = true;
		this.mexico.UseUnderline = true;
		this.fixed1.Add (this.mexico);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.mexico]));
		w18.X = 33;
		w18.Y = 248;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("b)");
		this.fixed1.Add (this.label11);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label11]));
		w19.X = 122;
		w19.Y = 248;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.españa = new global::Gtk.CheckButton ();
		this.españa.CanFocus = true;
		this.españa.Name = "españa";
		this.españa.Label = global::Mono.Unix.Catalog.GetString ("España");
		this.españa.DrawIndicator = true;
		this.españa.UseUnderline = true;
		this.fixed1.Add (this.españa);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.españa]));
		w20.X = 140;
		w20.Y = 248;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("c)");
		this.fixed1.Add (this.label12);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label12]));
		w21.X = 225;
		w21.Y = 247;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.japon = new global::Gtk.CheckButton ();
		this.japon.CanFocus = true;
		this.japon.Name = "japon";
		this.japon.Label = global::Mono.Unix.Catalog.GetString ("Japon");
		this.japon.DrawIndicator = true;
		this.japon.UseUnderline = true;
		this.fixed1.Add (this.japon);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.japon]));
		w22.X = 247;
		w22.Y = 248;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("d)");
		this.fixed1.Add (this.label13);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label13]));
		w23.X = 322;
		w23.Y = 249;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.argentina = new global::Gtk.CheckButton ();
		this.argentina.CanFocus = true;
		this.argentina.Name = "argentina";
		this.argentina.Label = global::Mono.Unix.Catalog.GetString ("Argentina");
		this.argentina.DrawIndicator = true;
		this.argentina.UseUnderline = true;
		this.fixed1.Add (this.argentina);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.argentina]));
		w24.X = 344;
		w24.Y = 249;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblpregunta4 = new global::Gtk.Label ();
		this.lblpregunta4.Name = "lblpregunta4";
		this.lblpregunta4.LabelProp = global::Mono.Unix.Catalog.GetString ("4-. Indique la fecha de la Independencia de Mexico.");
		this.fixed1.Add (this.lblpregunta4);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblpregunta4]));
		w25.X = 21;
		w25.Y = 289;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.calendario = new global::Gtk.Calendar ();
		this.calendario.CanFocus = true;
		this.calendario.Name = "calendario";
		this.calendario.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.fixed1.Add (this.calendario);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.calendario]));
		w26.X = 38;
		w26.Y = 317;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.botonterminar = new global::Gtk.Button ();
		this.botonterminar.CanFocus = true;
		this.botonterminar.Name = "botonterminar";
		this.botonterminar.UseUnderline = true;
		this.botonterminar.Label = global::Mono.Unix.Catalog.GetString ("Terminar");
		this.fixed1.Add (this.botonterminar);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.botonterminar]));
		w27.X = 304;
		w27.Y = 457;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry3 = new global::Gtk.Entry ();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '●';
		this.fixed1.Add (this.entry3);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry3]));
		w28.X = 373;
		w28.Y = 456;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 571;
		this.DefaultHeight = 540;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.botonterminar.Clicked += new global::System.EventHandler (this.OnBotonterminarClicked);
	}
}
